spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    schema: cuttlefern
    username: postgres
    password: bondstone
    initialize: true
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: cuttlefern